# Generated by Django 5.2 on 2026-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_radius',
            field=models.IntegerField(default=500),
        ),
    ]
