# Generated by Django 5.2.6 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_passwordhealth_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='browser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
