# Generated by Django 5.2.6 on 2026-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_loginlog_browser_loginlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vault_verifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
