# Generated by Django 5.2.6 on 2026-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_profile_vault_verifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], max_length=10),
        ),
    ]
