# Generated by Django 5.2.6 on 2026-06-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_trustedlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allowed_lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allowed_lng',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allowed_radius',
        ),
    ]
