# Generated by Django 5.2.6 on 2026-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_remove_profile_allowed_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
