# Generated by Django 5.2.6 on 2026-07-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_vaultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
